# Generated by Django 2.2.16 on 2020-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20201015_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
